FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

COPY requirements/trainer.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY requirements/api.txt requirements-api.txt
RUN pip install --no-cache-dir -r requirements-api.txt

COPY app/       ./app/
COPY services/  ./services/
RUN mkdir -p data

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

CMD ["python", "-m", "services.trainer.train", "--location", "London"]
